import React from "react";
import Head from "next/head";
import { NextSeo } from "next-seo";
import { siteMetadata } from "../../site/siteMetadata";

type Props = {
  children: React.ReactNode;
  title?: string;
};

const Layout = ({ children, title }: Props) => {
  return (
    <>
      <NextSeo
        title={`${siteMetadata.homeTitle}`}
        description={siteMetadata.description}
        canonical={siteMetadata.siteAddress}
        openGraph={{
          url: `${siteMetadata.siteAddress}`,
          title: `${siteMetadata.homeTitle}`,
          description: `${siteMetadata.description}`,
          images: [
            {
              url: "/login-page.png",
              // width: 800,
              // height: 600,
              alt: "home page",
              type: "image/png",
            },
            // { url: '/assets/site/home-light.svg' },
          ],
          site_name: `${siteMetadata.title}`,
        }}
        twitter={{
          handle: `${siteMetadata.twitter}`,
          site: `${siteMetadata.twitter}`,
          cardType: "summary_large_image",
        }}
      />
      <Head>
        {/* <title>{title ?? "Mypost but Github"}</title>
        <meta name="description" content="Generated by create-t3-app" /> */}
        {/* <link rel="icon" href="/favicon.ico" /> */}
        <link rel="icon" href="/paper-plane.png" />
      </Head>
      <main>{children}</main>
    </>
  );
};

export default Layout;
